export const CURRENCIES = [
  { code: "AED", name: "UAE dirham", flag: "🇦🇪", decimals: 2 },
  { code: "AFN", name: "Afghan afghani", flag: "🇦🇫", decimals: 2 },
  { code: "ALL", name: "Albanian lek", flag: "🇦🇱", decimals: 2 },
  { code: "AMD", name: "Armenian dram", flag: "🇦🇲", decimals: 2 },
  {
    code: "ANG",
    name: "Netherlands Antillean guilder",
    flag: "🇨🇼",
    decimals: 2,
  },
  { code: "AOA", name: "Angolan kwanza", flag: "🇦🇴", decimals: 2 },
  { code: "ARS", name: "Argentine peso", flag: "🇦🇷", decimals: 2 },
  { code: "AUD", name: "Australian dollar", flag: "🇦🇺", decimals: 2 },
  { code: "AWG", name: "Aruban florin", flag: "🇦🇼", decimals: 2 },
  { code: "AZN", name: "Azerbaijani manat", flag: "🇦🇿", decimals: 2 },
  { code: "BAM", name: "Bosnia-Herzegovina mark", flag: "🇧🇦", decimals: 2 },
  { code: "BBD", name: "Barbadian dollar", flag: "🇧🇧", decimals: 2 },
  { code: "BDT", name: "Bangladeshi taka", flag: "🇧🇩", decimals: 2 },
  { code: "BHD", name: "Bahraini dinar", flag: "🇧🇭", decimals: 3 },
  { code: "BIF", name: "Burundian franc", flag: "🇧🇮", decimals: 0 },
  { code: "BMD", name: "Bermudan dollar", flag: "🇧🇲", decimals: 2 },
  { code: "BND", name: "Brunei dollar", flag: "🇧🇳", decimals: 2 },
  { code: "BOB", name: "Bolivian boliviano", flag: "🇧🇴", decimals: 2 },
  { code: "BRL", name: "Brazilian real", flag: "🇧🇷", decimals: 2 },
  { code: "BSD", name: "Bahamian dollar", flag: "🇧🇸", decimals: 2 },
  { code: "BTN", name: "Bhutanese ngultrum", flag: "🇧🇹", decimals: 2 },
  { code: "BWP", name: "Botswanan pula", flag: "🇧🇼", decimals: 2 },
  { code: "BYN", name: "Belarusian ruble", flag: "🇧🇾", decimals: 2 },
  { code: "BZD", name: "Belize dollar", flag: "🇧🇿", decimals: 2 },
  { code: "CAD", name: "Canadian dollar", flag: "🇨🇦", decimals: 2 },
  { code: "CDF", name: "Congolese franc", flag: "🇨🇩", decimals: 2 },
  { code: "CHF", name: "Swiss franc", flag: "🇨🇭", decimals: 2 },
  { code: "CLP", name: "Chilean peso", flag: "🇨🇱", decimals: 0 },
  { code: "CNH", name: "Chinese yuan (offshore)", flag: "🇨🇳", decimals: 2 },
  { code: "CNY", name: "Chinese yuan", flag: "🇨🇳", decimals: 2 },
  { code: "COP", name: "Colombian peso", flag: "🇨🇴", decimals: 2 },
  { code: "CRC", name: "Costa Rican colón", flag: "🇨🇷", decimals: 2 },
  { code: "CUP", name: "Cuban peso", flag: "🇨🇺", decimals: 2 },
  { code: "CVE", name: "Cape Verdean escudo", flag: "🇨🇻", decimals: 2 },
  { code: "CZK", name: "Czech koruna", flag: "🇨🇿", decimals: 2 },
  { code: "DJF", name: "Djiboutian franc", flag: "🇩🇯", decimals: 0 },
  { code: "DKK", name: "Danish krone", flag: "🇩🇰", decimals: 2 },
  { code: "DOP", name: "Dominican peso", flag: "🇩🇴", decimals: 2 },
  { code: "DZD", name: "Algerian dinar", flag: "🇩🇿", decimals: 2 },
  { code: "EGP", name: "Egyptian pound", flag: "🇪🇬", decimals: 2 },
  { code: "ERN", name: "Eritrean nakfa", flag: "🇪🇷", decimals: 2 },
  { code: "ETB", name: "Ethiopian birr", flag: "🇪🇹", decimals: 2 },
  { code: "EUR", name: "Euro", flag: "🇪🇺", decimals: 2 },
  { code: "FJD", name: "Fijian dollar", flag: "🇫🇯", decimals: 2 },
  { code: "FKP", name: "Falkland Islands pound", flag: "🇫🇰", decimals: 2 },
  { code: "GBP", name: "British pound", flag: "🇬🇧", decimals: 2 },
  { code: "GEL", name: "Georgian lari", flag: "🇬🇪", decimals: 2 },
  { code: "GGP", name: "Guernsey pound", flag: "🇬🇬", decimals: 2 },
  { code: "GHS", name: "Ghanaian cedi", flag: "🇬🇭", decimals: 2 },
  { code: "GIP", name: "Gibraltar pound", flag: "🇬🇮", decimals: 2 },
  { code: "GMD", name: "Gambian dalasi", flag: "🇬🇲", decimals: 2 },
  { code: "GNF", name: "Guinean franc", flag: "🇬🇳", decimals: 0 },
  { code: "GTQ", name: "Guatemalan quetzal", flag: "🇬🇹", decimals: 2 },
  { code: "GYD", name: "Guyanaese dollar", flag: "🇬🇾", decimals: 2 },
  { code: "HKD", name: "Hong Kong dollar", flag: "🇭🇰", decimals: 2 },
  { code: "HNL", name: "Honduran lempira", flag: "🇭🇳", decimals: 2 },
  { code: "HTG", name: "Haitian gourde", flag: "🇭🇹", decimals: 2 },
  { code: "HUF", name: "Hungarian forint", flag: "🇭🇺", decimals: 2 },
  { code: "IDR", name: "Indonesian rupiah", flag: "🇮🇩", decimals: 2 },
  { code: "ILS", name: "Israeli new shekel", flag: "🇮🇱", decimals: 2 },
  { code: "IMP", name: "Isle of Man pound", flag: "🇮🇲", decimals: 2 },
  { code: "INR", name: "Indian rupee", flag: "🇮🇳", decimals: 2 },
  { code: "IQD", name: "Iraqi dinar", flag: "🇮🇶", decimals: 3 },
  { code: "IRR", name: "Iranian rial", flag: "🇮🇷", decimals: 2 },
  { code: "ISK", name: "Icelandic króna", flag: "🇮🇸", decimals: 0 },
  { code: "JEP", name: "Jersey pound", flag: "🇯🇪", decimals: 2 },
  { code: "JMD", name: "Jamaican dollar", flag: "🇯🇲", decimals: 2 },
  { code: "JOD", name: "Jordanian dinar", flag: "🇯🇴", decimals: 3 },
  { code: "JPY", name: "Japanese yen", flag: "🇯🇵", decimals: 0 },
  { code: "KES", name: "Kenyan shilling", flag: "🇰🇪", decimals: 2 },
  { code: "KGS", name: "Kyrgystani som", flag: "🇰🇬", decimals: 2 },
  { code: "KHR", name: "Cambodian riel", flag: "🇰🇭", decimals: 2 },
  { code: "KMF", name: "Comorian franc", flag: "🇰🇲", decimals: 0 },
  { code: "KRW", name: "South Korean won", flag: "🇰🇷", decimals: 0 },
  { code: "KWD", name: "Kuwaiti dinar", flag: "🇰🇼", decimals: 3 },
  { code: "KYD", name: "Cayman Islands dollar", flag: "🇰🇾", decimals: 2 },
  { code: "KZT", name: "Kazakhstani tenge", flag: "🇰🇿", decimals: 2 },
  { code: "LAK", name: "Laotian kip", flag: "🇱🇦", decimals: 2 },
  { code: "LBP", name: "Lebanese pound", flag: "🇱🇧", decimals: 2 },
  { code: "LKR", name: "Sri Lankan rupee", flag: "🇱🇰", decimals: 2 },
  { code: "LRD", name: "Liberian dollar", flag: "🇱🇷", decimals: 2 },
  { code: "LSL", name: "Lesotho loti", flag: "🇱🇸", decimals: 2 },
  { code: "LYD", name: "Libyan dinar", flag: "🇱🇾", decimals: 3 },
  { code: "MAD", name: "Moroccan dirham", flag: "🇲🇦", decimals: 2 },
  { code: "MDL", name: "Moldovan leu", flag: "🇲🇩", decimals: 2 },
  { code: "MGA", name: "Malagasy ariary", flag: "🇲🇬", decimals: 2 },
  { code: "MKD", name: "Macedonian denar", flag: "🇲🇰", decimals: 2 },
  { code: "MMK", name: "Myanmar kyat", flag: "🇲🇲", decimals: 2 },
  { code: "MNT", name: "Mongolian tugrik", flag: "🇲🇳", decimals: 2 },
  { code: "MOP", name: "Macanese pataca", flag: "🇲🇴", decimals: 2 },
  { code: "MRU", name: "Mauritanian ouguiya", flag: "🇲🇷", decimals: 2 },
  { code: "MUR", name: "Mauritian rupee", flag: "🇲🇺", decimals: 2 },
  { code: "MVR", name: "Maldivian rufiyaa", flag: "🇲🇻", decimals: 2 },
  { code: "MWK", name: "Malawian kwacha", flag: "🇲🇼", decimals: 2 },
  { code: "MXN", name: "Mexican peso", flag: "🇲🇽", decimals: 2 },
  { code: "MYR", name: "Malaysian ringgit", flag: "🇲🇾", decimals: 2 },
  { code: "MZN", name: "Mozambican metical", flag: "🇲🇿", decimals: 2 },
  { code: "NAD", name: "Namibian dollar", flag: "🇳🇦", decimals: 2 },
  { code: "NGN", name: "Nigerian naira", flag: "🇳🇬", decimals: 2 },
  { code: "NIO", name: "Nicaraguan córdoba", flag: "🇳🇮", decimals: 2 },
  { code: "NOK", name: "Norwegian krone", flag: "🇳🇴", decimals: 2 },
  { code: "NPR", name: "Nepalese rupee", flag: "🇳🇵", decimals: 2 },
  { code: "NZD", name: "New Zealand dollar", flag: "🇳🇿", decimals: 2 },
  { code: "OMR", name: "Omani rial", flag: "🇴🇲", decimals: 3 },
  { code: "PAB", name: "Panamanian balboa", flag: "🇵🇦", decimals: 2 },
  { code: "PEN", name: "Peruvian sol", flag: "🇵🇪", decimals: 2 },
  { code: "PGK", name: "Papua New Guinean kina", flag: "🇵🇬", decimals: 2 },
  { code: "PHP", name: "Philippine peso", flag: "🇵🇭", decimals: 2 },
  { code: "PKR", name: "Pakistani rupee", flag: "🇵🇰", decimals: 2 },
  { code: "PLN", name: "Polish złoty", flag: "🇵🇱", decimals: 2 },
  { code: "PYG", name: "Paraguayan guarani", flag: "🇵🇾", decimals: 0 },
  { code: "QAR", name: "Qatari rial", flag: "🇶🇦", decimals: 2 },
  { code: "RON", name: "Romanian leu", flag: "🇷🇴", decimals: 2 },
  { code: "RSD", name: "Serbian dinar", flag: "🇷🇸", decimals: 2 },
  { code: "RUB", name: "Russian ruble", flag: "🇷🇺", decimals: 2 },
  { code: "RWF", name: "Rwandan franc", flag: "🇷🇼", decimals: 0 },
  { code: "SAR", name: "Saudi riyal", flag: "🇸🇦", decimals: 2 },
  { code: "SBD", name: "Solomon Islands dollar", flag: "🇸🇧", decimals: 2 },
  { code: "SCR", name: "Seychellois rupee", flag: "🇸🇨", decimals: 2 },
  { code: "SDG", name: "Sudanese pound", flag: "🇸🇩", decimals: 2 },
  { code: "SEK", name: "Swedish krona", flag: "🇸🇪", decimals: 2 },
  { code: "SGD", name: "Singapore dollar", flag: "🇸🇬", decimals: 2 },
  { code: "SHP", name: "St Helena pound", flag: "🇸🇭", decimals: 2 },
  { code: "SLE", name: "Sierra Leonean leone", flag: "🇸🇱", decimals: 2 },
  { code: "SOS", name: "Somali shilling", flag: "🇸🇴", decimals: 2 },
  { code: "SRD", name: "Surinamese dollar", flag: "🇸🇷", decimals: 2 },
  { code: "SSP", name: "South Sudanese pound", flag: "🇸🇸", decimals: 2 },
  { code: "STN", name: "São Tomé and Príncipe dobra", flag: "🇸🇹", decimals: 2 },
  { code: "SVC", name: "Salvadoran colón", flag: "🇸🇻", decimals: 2 },
  { code: "SYP", name: "Syrian pound", flag: "🇸🇾", decimals: 2 },
  { code: "SZL", name: "Swazi lilangeni", flag: "🇸🇿", decimals: 2 },
  { code: "THB", name: "Thai baht", flag: "🇹🇭", decimals: 2 },
  { code: "TJS", name: "Tajikistani somoni", flag: "🇹🇯", decimals: 2 },
  { code: "TMT", name: "Turkmenistani manat", flag: "🇹🇲", decimals: 2 },

  { code: "TND", name: "Tunisian dinar", flag: "🇹🇳", decimals: 3 },
  { code: "TOP", name: "Tongan paʻanga", flag: "🇹🇴", decimals: 2 },
  { code: "TRY", name: "Turkish lira", flag: "🇹🇷", decimals: 2 },
  { code: "TTD", name: "Trinidad and Tobago dollar", flag: "🇹🇹", decimals: 2 },
  { code: "TWD", name: "New Taiwan dollar", flag: "🇹🇼", decimals: 2 },
  { code: "TZS", name: "Tanzanian shilling", flag: "🇹🇿", decimals: 2 },
  { code: "UAH", name: "Ukrainian hryvnia", flag: "🇺🇦", decimals: 2 },
  { code: "UGX", name: "Ugandan shilling", flag: "🇺🇬", decimals: 0 },
  { code: "USD", name: "US dollar", flag: "🇺🇸", decimals: 2 },
  { code: "UYU", name: "Uruguayan peso", flag: "🇺🇾", decimals: 2 },
  { code: "UZS", name: "Uzbekistani som", flag: "🇺🇿", decimals: 2 },
  { code: "VES", name: "Venezuelan bolívar", flag: "🇻🇪", decimals: 2 },
  { code: "VND", name: "Vietnamese dong", flag: "🇻🇳", decimals: 0 },
  { code: "VUV", name: "Vanuatu vatu", flag: "🇻🇺", decimals: 0 },
  { code: "WST", name: "Samoan tala", flag: "🇼🇸", decimals: 2 },
  { code: "XAF", name: "Central African CFA franc", flag: "🌍", decimals: 0 },
  { code: "XCD", name: "East Caribbean dollar", flag: "🌎", decimals: 2 },
  { code: "XCG", name: "Caribbean guilder", flag: "🌎", decimals: 2 },
  { code: "XOF", name: "West African CFA franc", flag: "🌍", decimals: 0 },
  { code: "XPF", name: "CFP franc", flag: "🌏", decimals: 0 },
  { code: "YER", name: "Yemeni rial", flag: "🇾🇪", decimals: 2 },
  { code: "ZAR", name: "South African rand", flag: "🇿🇦", decimals: 2 },
  { code: "ZMW", name: "Zambian kwacha", flag: "🇿🇲", decimals: 2 },
  { code: "ZWG", name: "Zimbabwe gold", flag: "🇿🇼", decimals: 2 },
] as const;

export type Currency = (typeof CURRENCIES)[number];
export type CurrencyCode = Currency["code"];

export const POPULAR: CurrencyCode[] = [
  "EUR",
  "USD",
  "GBP",
  "CHF",
  "JPY",
  "AUD",
];
